[package]
name = "visa"
version = "0.1.1"
edition = "2024"

[dependencies]
thiserror = { version = "2.0" }
bitflags = { version = "2.9" }
regex = { version = "1.11" }

[build-dependencies]
bindgen = { version = "0.71" }
