[package]
name = "visa"
version = "0.2.0"
edition = "2024"

[features]

[dependencies]
thiserror = "2.0"
bitflags = "2.9"
regex = "1.11"
tracing = "0.1.41"

[build-dependencies]
bindgen = "0.71"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
